In [2]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [5]:
y=np.arange(0,20,3)
print(y)

[ 0  3  6  9 12 15 18]


In [6]:
z1=np.arange(0,20)
z1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.random.random((2,3))

array([[0.47669868, 0.64423059, 0.53619458],
       [0.2679519 , 0.6441816 , 0.5062977 ]])

In [19]:
np.random.randint(0,20,(3,4))

array([[17, 17, 18, 12],
       [19, 17, 15, 11],
       [10, 17,  3,  9]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.random(10)

array([0.63351275, 0.53550251, 0.96204509, 0.20275568, 0.59286879,
       0.88354008, 0.05362838, 0.64365706, 0.53190662, 0.79874491])

In [23]:
np.random.randint(1,100,10)

array([ 7, 44, 58, 78, 45, 67, 47, 96, 79, 22])

In [25]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
xy=arr.reshape((4,5))
xy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
xy.max()

19

In [31]:
print(arr.shape)
print(xy.shape)

(20,)
(4, 5)


In [32]:
xy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
xy[0,1]

1

In [34]:
xy[2:,:3]

array([[10, 11, 12],
       [15, 16, 17]])

In [35]:
xy>3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
np.sqrt(xy)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])